logging.level:
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  config:
    import:
      - "another.yml"
      - "optional:file:./spring-mvc/dev/external-config.yml"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: ${spring.application.name}
      group-id: ${spring.application.name}-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

myapp:
  client:
    http:
      baseUrl: http//localhost:9000
      connectionTimeoutMillis: 3000
      readTimeoutMillis: 3000
    kafka:
      enable: true

  configTest:
    key: value
    env_test: ${ENV_TEST}
    noenv: ${NO_ENV:default_value}
    flag: true
    env: no_env
