---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mockServer:
    image: wiremock/wiremock:latest-alpine
    volumes:
      - "./dev/wiremock/:/home/wiremock/"
    ports:
      - 9000:8080
    restart: on-failure
    command:
      - --verbose
      - --disable-banner

  redis:
    image: "redis:6.2.8"
    ports:
      - "6379:6379"
    volumes:
      - ./dev/redis:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: miniopass
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: miniopass
    command:
      [
        'minio',
        'server',
        '/export',
        '--address',
        ':9050',
        '--console-address',
        ':9051'
      ]
    ports:
      - '9050:9050'
      - '9051:9051'

  create_bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " until (/usr/bin/mc config host add myminio http://minio:9050 root miniopass) do echo '...waiting...' && sleep 1; done; /usr/bin/mc mb myminio/mybucket; /usr/bin/mc anonymous set download myminio/mybucket; exit 0; "

